insert into public.projects (
  title,
  slug,
  description,
  cover_image_url,
  cover_display,
  product_overview,
  gallery_image_urls,
  video_url,
  product_role,
  product_features,
  product_results,
  tech_stack,
  project_url,
  repo_url,
  featured,
  "order"
)
values
  (
    'Atlas CRM',
    'atlas-crm',
    'Painel operacional para equipes comerciais acompanharem pipeline, receita e tarefas críticas em tempo real.',
    '/project-atlas.svg',
    'thumbnail',
    'Um CRM operacional pensado para diminuir ruído entre leads, atividades e decisões de venda. A experiência concentra indicadores, próximos passos e contexto do cliente em uma interface rápida de escanear.',
    array['/project-atlas.svg'],
    null,
    'Full-stack developer',
    array['Pipeline visual', 'Indicadores em tempo real', 'Gestão de tarefas comerciais'],
    array['Menos troca de contexto', 'Leitura rápida do funil', 'Operação preparada para times pequenos'],
    array['Next.js', 'Supabase', 'TypeScript'],
    null,
    null,
    true,
    1
  ),
  (
    'Pulse Analytics',
    'pulse-analytics',
    'Dashboard de produto com métricas acionáveis, segmentação por coorte e visualizações focadas em decisão.',
    '/project-pulse.svg',
    'thumbnail',
    'Uma camada analítica para transformar eventos de produto em leitura objetiva. O foco é revelar padrões de uso, retenção e oportunidades sem enterrar o usuário em gráficos soltos.',
    array['/project-pulse.svg'],
    null,
    'Frontend e visual analytics',
    array['Coortes', 'Métricas de produto', 'Visualizações responsivas'],
    array['Decisões mais rápidas', 'Sinais de retenção claros', 'Painel pronto para apresentação'],
    array['React', 'Postgres', 'GSAP'],
    null,
    null,
    true,
    2
  ),
  (
    'Forge Admin',
    'forge-admin',
    'Área administrativa enxuta para gerenciar conteúdo, uploads e estados de publicação sem tocar no código.',
    '/project-forge.svg',
    'thumbnail',
    'Um painel privado para controlar conteúdo de projetos com autenticação, uploads e estados de destaque. A proposta é dar autonomia sem transformar o site em um CMS genérico.',
    array['/project-forge.svg'],
    null,
    'Arquitetura e implementação',
    array['Auth', 'CRUD de projetos', 'Upload de imagens'],
    array['Conteúdo editável pelo painel', 'Menos manutenção manual', 'Base pronta para evoluir'],
    array['Next.js', 'Storage', 'Auth'],
    null,
    null,
    false,
    3
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  cover_image_url = excluded.cover_image_url,
  cover_display = excluded.cover_display,
  product_overview = excluded.product_overview,
  gallery_image_urls = excluded.gallery_image_urls,
  video_url = excluded.video_url,
  product_role = excluded.product_role,
  product_features = excluded.product_features,
  product_results = excluded.product_results,
  tech_stack = excluded.tech_stack,
  project_url = excluded.project_url,
  repo_url = excluded.repo_url,
  featured = excluded.featured,
  "order" = excluded."order";
